title: JSesh Documentation
metadata:
    description: 'JSesh Documentation'
author:
  name: Serge Rosmorduc
  email: 'serge.rosmorduc@qenherkhopeshef.org'
taxonomies: [category,tag]
summary:
  size: 300

