title: SITE_NAME
metadata:
    description: 'JSesh Documentation'
author:
  name: Serge Rosmorduc
  email: 'serge.rosmorduc@qenherkhopeshef.org'
taxonomies: [category,tag,author]
summary:
  size: 300

